export const menu = [
    {
        code: 'something',
        gmtCreate: '创建时间',
        gmtModified: '修改时间',
        icon: 'QrcodeOutlined',
        id: 1,
        isDelete: 0,
        isIncludeSubmenu: 1,
        level: 1,
        menuName: '菜单名字',
        orders: 1,
        pageLink: 'undefined',
        path: '/dataCenter',
        status: 1,
        systemCode: 'sword-heart',
        userId: 1,
        userName: '剑心',
        children: [
            {
                code: "table_view",
                gmtCreate: 1630586370000,
                gmtModified: 1638774253000,
                icon: "BuildOutlined",
                id: 2,
                isDelete: 0,
                isIncludeSubmenu: 0,
                level: 2,
                menuName: "菜单1",
                orders: 1,
                pCode: "data_center",
                pageLink: "39ae6aa3",
                path: "/tableView",
                status: 1,
                systemCode: "iwork",
                userId: 1,
                userName: "root"
            },
            {
                code: "table_manage",
                gmtCreate: 1630586360000,
                gmtModified: 1638774253000,
                icon: "data",
                id: 6,
                isDelete: 0,
                isIncludeSubmenu: 0,
                level: 2,
                menuName: "菜单2",
                orders: 2,
                pCode: "data_center",
                pageLink: "c9e66a7a",
                path: "/tableManage",
                status: 1,
                systemCode: "iwork",
                userId: 1,
                userName: "root"
            },
        ]
    }
]